import Image from 'next/image'
import Head from 'next/head'
import Link from 'next/link'
import clsx from 'clsx'
import { Prose } from '@/components/Prose'
import { Container } from '@/components/Container'
import {
  TwitterIcon,
  InstagramIcon,
  GitHubIcon,
  LinkedInIcon,
} from '@/components/SocialIcons'
import portraitImage from '@/images/portrait.jpg'

function SocialLink({ className, href, children, icon: Icon }) {
  return (
    <li className={clsx(className, 'flex')}>
      <Link
        href={href}
        className="group flex text-sm font-medium text-zinc-800 transition hover:text-teal-500 dark:text-zinc-200 dark:hover:text-teal-500"
      >
        <Icon className="h-6 w-6 flex-none fill-zinc-500 transition group-hover:fill-teal-500" />
        <span className="ml-4">{children}</span>
      </Link>
    </li>
  )
}

function MailIcon(props) {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" {...props}>
      <path
        fillRule="evenodd"
        d="M6 5a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h12a3 3 0 0 0 3-3V8a3 3 0 0 0-3-3H6Zm.245 2.187a.75.75 0 0 0-.99 1.126l6.25 5.5a.75.75 0 0 0 .99 0l6.25-5.5a.75.75 0 0 0-.99-1.126L12 12.251 6.245 7.187Z"
      />
    </svg>
  )
}

export default function About() {
  return (
    <>
      <Head>
        <title>About - Mikey Shean</title>
        <meta
          name="description"
          content="I’m Mikey Shean. I live in New York City, where I design the future."
        />
      </Head>
      <Container className="mt-16 sm:mt-32">
        <div className="grid grid-cols-1 gap-y-16 lg:grid-cols-2 lg:grid-rows-[auto_1fr] lg:gap-y-12">
          <div className="lg:pl-20">
            <div className="max-w-xs px-2.5 lg:max-w-none">
              <figure>
                <Image
                  src={portraitImage}
                  alt=""
                  priority
                  sizes="(min-width: 1024px) 32rem, 20rem"
                  className="aspect-square rotate-3 rounded-2xl bg-zinc-100 object-cover dark:bg-zinc-800"
                />
                <Prose>
                  <div className="flex justify-center mt-2 mb-0">
                    <figcaption>Portrait of me as an astronaut 👨‍🚀 (Generated by AI)</figcaption>
                  </div>
                  <div className="flex justify-center mt-0 mb-0">
                    <figcaption className='mt-0'><em>Disclaimer: I have never actually been an astronaut</em> </figcaption>
                  </div>
                </Prose>
              </figure>
            </div>
          </div>
          <div className="lg:order-first lg:row-span-2">
            <h1 className="text-4xl font-bold tracking-tight text-zinc-800 dark:text-zinc-100 sm:text-5xl">
              About Me
            </h1>
            <div className="mt-6 space-y-7 text-base text-zinc-600 dark:text-zinc-400">
              
              <p>
                Hi! My name is Mikey, and my interest in web development started like so many 
                others: By building custom themes for my MySpace and Xanga (+2 eProps for you, if 
                you know what eProps are!). Although it was only HTML and CSS, it was the 
                perfect introduction to the world of computer science, and it would ultimately 
                lead me to pursue it as a career.
              </p>
              <p>
                Since then, I&apos;ve had the amazing opportunity to work with both fast-paced startups and larger 
                organizations.  Coincidentally, many have been involved in the travel industry in one form or another.  My main 
                focus these days has been exploring domains that I&apos;m not as familiar with whether it be ML/AI, newer frontend frameworks, or getting 
                into the finer details of DevOps and Cloud Infrastructure.
              </p>
              <p>  
                Although I specialize in the backend of the stack, I&apos;ve been returning to my roots lately 
                and feeding my original passion for the frontend.  This site you&apos;re visiting  
                right now is one of my first projects deployed with Next.js and I&apos;m 
                loving how far frontend frameworks have come since I first got started.
              </p>
              <Prose>
                <p>
                  If you&apos;d like to learn more about the things I&apos;m working on, please check 
                  out my <Link href="/projects">projects</Link> and <Link href="/blog">blog</Link>.
                </p>
              </Prose>
              <p>
                Here are a few technologies I&apos;ve been working with recently:
              </p>
                <ul className='arrow columns-2'>
                  <li>Next.js</li>
                  <li>React</li>
                  <li>TypeScript</li>
                  <li>TailwindCSS</li>
                  <li>Python & Django</li>
                  <li>tRPC & Prisma</li>
                  <li>AWS Copilot for Cloud Infrastructure</li>
                </ul>
            </div>
          </div>
          <div className="lg:pl-20">
            <ul role="list">
              {/* <SocialLink href="#" icon={TwitterIcon}>
                Follow on Twitter
              </SocialLink>
              <SocialLink href="#" icon={InstagramIcon} className="mt-4">
                Follow on Instagram
              </SocialLink> */}
              <SocialLink href="https://github.com/mikeyshean" icon={GitHubIcon} className="mt-4">
                Follow on GitHub
              </SocialLink>
              <SocialLink href="https://linkedin.com/in/mdshean/" icon={LinkedInIcon} className="mt-4">
                Follow on LinkedIn
              </SocialLink>
              <SocialLink
                href="mailto:hello@mikeyshean.com"
                icon={MailIcon}
                className="mt-8 border-t border-zinc-100 pt-8 dark:border-zinc-700/40"
              >
                hello@mikeyshean.com
              </SocialLink>
            </ul>
          </div>
        </div>
      </Container>
    </>
  )
}
